apiVersion: v1
kind: Service
metadata:
  name: troas-customer-api-app-svc
  namespace: troas-customer-api-ns
spec:
  selector:
    app: troas-customer-api-app
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the service
      targetPort: http # Port name exposed by the container
  type: LoadBalancer
